# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Enraged\:
        resource: '../src/Enraged/'
        exclude:
            - '../src/Enraged/Domain/'
            - '../src/Enraged/Infrastructure/Framework/Kernel.php'

    # APPLICATION/QUERY/DOCTORS/EXTERNAL-DOCTORS
    Enraged\Application\Query\Doctor\ExternalDoctors\ExternalDoctorsQueryInterface:
        class: 'Enraged\Infrastructure\HTTP\DoctorsApi\ExternalDoctorsApiClient'
        arguments:
            $api_host: '%env(DOCTORS_API_HOST)%'
            $username: '%env(DOCTORS_API_USERNAME)%'
            $password: '%env(DOCTORS_API_PASSWORD)%'

    # DOMAIN => ORM
    Enraged\Domain\Doctor\DoctorInterface:
        alias: 'Enraged\Infrastructure\ORM\DoctorOrm'

    # INTERACTIONS/WEB
    Enraged\Interactions\Web\Controller\:
        resource: '../src/Enraged/Interactions/Web/Controller'
        tags: ['controller.service_arguments']

    # INFRASTRUCTURE/CALENDAR
    Enraged\Infrastructure\Calendar\CalendarInterface:
        class: 'Enraged\Infrastructure\Calendar\Calendar'

    # INFRASTRUCTURE/BUS
    Enraged\Application\CommandHandler\:
        resource: '../src/Enraged/Application/CommandHandler/'
        tags: [{ name: 'messenger.message_handler', bus: 'command.bus' }]

    Enraged\Application\QueryHandler\:
        resource: '../src/Enraged/Application/QueryHandler/'
        tags: [{ name: 'messenger.message_handler', bus: 'query.bus' }]

    Enraged\Application\EventHandler\:
        resource: '../src/Enraged/Application/EventHandler/'
        tags: [{ name: 'messenger.message_handler', bus: 'event.bus' }]

    # INFRASTRUCTURE/HTTP
    Symfony\Component\HttpClient\TraceableHttpClient: ~
    Enraged\Infrastructure\HTTP\Client\HttpClientInterface:
        class: 'Enraged\Infrastructure\HTTP\Client\HttpClient'
        public: true
        arguments:
            - '@Symfony\Component\HttpClient\TraceableHttpClient'

